server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: cambio-service
        uri: lb://CAMBIO-SERVICE
        predicates:
          - Path=/cambio-service/**
      - id: book-service
        uri: lb://BOOK-SERVICE
        predicates:
          - Path=/book-service/**
      #criado para o swagger do api gateway mostrando os servicos para os clientes
      - id: openapi
        uri: lb://API-GATEWAY
        predicates:
          - Path=/v3/api-docs/**
        filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,metrics,prometheus,info"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    baggage:
      enabled: true