server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,metrics,prometheus,info"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  #cloud:
  #  gateway:
  #    discovery:
  #      locator:
  #        enabled: true
  #        lower-case-service-id: true
