server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: prod
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,metrics,prometheus,info"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

greeting-service:
  greeting: "Olá"
  default-value: "Mundo"

