server:
  port: 8082

spring:
  application:
    name: greeting-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: qa

greeting-service:
  greeting: "ola"
  default-value: "mundo greeting"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

