server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 3
        limit-refresh-period: 20s
  retry:
    instances:
      foobar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dockerMySql:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dockerMySql:3306/
    schemas: book_service
    user: root
    password: root
    locations:
      classpath: src/main/resources/db/migration

springdoc:
  show-actuator: true
  #swagger-ui:
    #path: /book-service/swagger-ui/
  api-docs:
    path: book-service/v3/api-docs

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,metrics,prometheus,info"
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/zipkin/
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    baggage:
      enabled: true



#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - '*'


