server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaelsoaresneves/microservice-spring.git
          default-label: master
#  profiles:
#    active:
#      - native

greeting-service:
  greeting: "ola"
  default-value: "mundo"