version: '3.8'

networks:
  localNetwork:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: dockerMySql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cambio_service
      MYSQL_USER: rafa
      MYSQL_PASSWORD: 12345
      #MYSQL_ROOT_HOST: 172.19.0.1
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - localNetwork

  #Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
    networks:
      - localNetwork
    ports:
      - 9090:9090
    expose:
      - 9090

  #Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - localNetwork

volumes:
  my-db:
  prometheus_data: {}
  grafana_data: {}