global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
# scrape metrics from the prometheus server itself
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
#
  - job_name: book-service
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8100
          - host.docker.internal:8101
        labels:
          application: "book-service"
#
  - job_name: cambio-service
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8000
          - host.docker.internal:8001
        labels:
          application: "cambio-service"


